//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChargeHub.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChargeHub.Resource.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tồn tại {0}..
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập thông tin tài khoản Ngân hàng..
        /// </summary>
        public static string BANK_ACCOUNT_INFO_REQUIRED {
            get {
                return ResourceManager.GetString("BANK_ACCOUNT_INFO_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tài khoản ngân hàng đã tồn tại..
        /// </summary>
        public static string BankAccountInformationExists {
            get {
                return ResourceManager.GetString("BankAccountInformationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gói thuê pin đã tồn tại.
        /// </summary>
        public static string BATTERY_PACKAGE_EXISTED {
            get {
                return ResourceManager.GetString("BATTERY_PACKAGE_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin hợp đồng thuê pin..
        /// </summary>
        public static string BATTERY_SUBSCRIPTION_NOTFOUND {
            get {
                return ResourceManager.GetString("BATTERY_SUBSCRIPTION_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số hợp đồng đã tồn tại.
        /// </summary>
        public static string BatterySubscriptionContractNoExists {
            get {
                return ResourceManager.GetString("BatterySubscriptionContractNoExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập thông tin mã hợp đồng.
        /// </summary>
        public static string BatterySubscriptionContractNoRequired {
            get {
                return ResourceManager.GetString("BatterySubscriptionContractNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn khách hàng..
        /// </summary>
        public static string BatterySubscriptionCustomerIdRequired {
            get {
                return ResourceManager.GetString("BatterySubscriptionCustomerIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập họ tên khách hàng..
        /// </summary>
        public static string BatterySubscriptionFullNameRequired {
            get {
                return ResourceManager.GetString("BatterySubscriptionFullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy gói cước tương ứng với mẫu xe.
        /// </summary>
        public static string BatterySubscriptionNotFoundPackageId {
            get {
                return ResourceManager.GetString("BatterySubscriptionNotFoundPackageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn gói cước..
        /// </summary>
        public static string BatterySubscriptionPackageRequired {
            get {
                return ResourceManager.GetString("BatterySubscriptionPackageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập thông tin mã khách hàng SAP.
        /// </summary>
        public static string BatterySubscriptionSapCustomerIdRequired {
            get {
                return ResourceManager.GetString("BatterySubscriptionSapCustomerIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xe đã tồn tại hợp đồng hoạt động.
        /// </summary>
        public static string BatterySubscriptionVehicleIdExists {
            get {
                return ResourceManager.GetString("BatterySubscriptionVehicleIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn xe..
        /// </summary>
        public static string BatterySubscriptionVehicleIdRequired {
            get {
                return ResourceManager.GetString("BatterySubscriptionVehicleIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy hoá đơn điều chỉnh.
        /// </summary>
        public static string BILL_ADJUSTMENT_NOTFOUND {
            get {
                return ResourceManager.GetString("BILL_ADJUSTMENT_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy số hoá đơn.
        /// </summary>
        public static string BILL_ID_NOTFOUND {
            get {
                return ResourceManager.GetString("BILL_ID_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thay đổi trạng thái ký phụ lục hợp đồng nếu đã ký hợp đồng trước đó.
        /// </summary>
        public static string CAN_NOT_UNSIGN_SUBCONTRACT {
            get {
                return ResourceManager.GetString("CAN_NOT_UNSIGN_SUBCONTRACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày áp dụng không được để trống hoặc nhỏ hơn ngày hiện tại.
        /// </summary>
        public static string ChargingConfigurationAppliedDate {
            get {
                return ResourceManager.GetString("ChargingConfigurationAppliedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá áp dụng phải lớn hơn 0.
        /// </summary>
        public static string ChargingConfigurationAppliedPrice {
            get {
                return ResourceManager.GetString("ChargingConfigurationAppliedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi đóng hợp đồng thuê pin..
        /// </summary>
        public static string CLOSE_LEASING_FAILED {
            get {
                return ResourceManager.GetString("CLOSE_LEASING_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số hợp đồng đã tồn tại.
        /// </summary>
        public static string CONTRACTNO_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("CONTRACTNO_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi khi tính toán tổng số bản ghi.
        /// </summary>
        public static string COUNTBY_SPEC_ERROR {
            get {
                return ResourceManager.GetString("COUNTBY_SPEC_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi tạo hợp đồng.
        /// </summary>
        public static string CREATE_LEASING_FAILED {
            get {
                return ResourceManager.GetString("CREATE_LEASING_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi khi tạo {0}..
        /// </summary>
        public static string CreatedError {
            get {
                return ResourceManager.GetString("CreatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin khách hàng..
        /// </summary>
        public static string CUSTOMER_INFO_NOTFOUND {
            get {
                return ResourceManager.GetString("CUSTOMER_INFO_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi xoá dữ liệu..
        /// </summary>
        public static string DELETE_DOC_ERROR {
            get {
                return ResourceManager.GetString("DELETE_DOC_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi thực thi tác vụ..
        /// </summary>
        public static string ESCOOTER_INVOICE_SAP_JOB_FAILED {
            get {
                return ResourceManager.GetString("ESCOOTER_INVOICE_SAP_JOB_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vượt quá độ dài do phép..
        /// </summary>
        public static string EXCEED_MAX_LENGTH {
            get {
                return ResourceManager.GetString("EXCEED_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi thực thi tác vụ..
        /// </summary>
        public static string EXECUTE_JOB_FAILED {
            get {
                return ResourceManager.GetString("EXECUTE_JOB_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xe này đã có hợp đồng thuê pin..
        /// </summary>
        public static string ExistedSubscriptionByVehicle {
            get {
                return ResourceManager.GetString("ExistedSubscriptionByVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi tìm dữ liệu.
        /// </summary>
        public static string FINDBY_SPEC_ERROR {
            get {
                return ResourceManager.GetString("FINDBY_SPEC_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra..
        /// </summary>
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi xảy ra. .
        /// </summary>
        public static string GeneralNotDefinedError {
            get {
                return ResourceManager.GetString("GeneralNotDefinedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi xảy ra {0} .
        /// </summary>
        public static string GeneralNotDefinedErrorWithParam {
            get {
                return ResourceManager.GetString("GeneralNotDefinedErrorWithParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi tìm dữ liệu.
        /// </summary>
        public static string GETBY_SPEC_ERROR {
            get {
                return ResourceManager.GetString("GETBY_SPEC_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy hashkey..
        /// </summary>
        public static string HASHKEY_NOT_FOUND_5005 {
            get {
                return ResourceManager.GetString("HASHKEY_NOT_FOUND_5005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi thêm dữ liệu..
        /// </summary>
        public static string INSERT_DOC_ERROR {
            get {
                return ResourceManager.GetString("INSERT_DOC_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể điều chỉnh hóa đơn điều chỉnh..
        /// </summary>
        public static string INVALID_BILL_ADJUSTMENT {
            get {
                return ResourceManager.GetString("INVALID_BILL_ADJUSTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số tiền thanh toán phải lớn hơn 0..
        /// </summary>
        public static string INVALID_BILL_AMOUNT {
            get {
                return ResourceManager.GetString("INVALID_BILL_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đơn hàng không hợp lệ..
        /// </summary>
        public static string INVALID_BILL_ID {
            get {
                return ResourceManager.GetString("INVALID_BILL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin code không hợp lệ.
        /// </summary>
        public static string INVALID_BIN_CODE {
            get {
                return ResourceManager.GetString("INVALID_BIN_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số thẻ không hợp lệ.
        /// </summary>
        public static string INVALID_CARD_NUMBER {
            get {
                return ResourceManager.GetString("INVALID_CARD_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách trụ sac không hợp lệ.
        /// </summary>
        public static string INVALID_CHARGINGSTATIONS_LIST {
            get {
                return ResourceManager.GetString("INVALID_CHARGINGSTATIONS_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin công ty không hợp lệ..
        /// </summary>
        public static string INVALID_COMPANY_INFO {
            get {
                return ResourceManager.GetString("INVALID_COMPANY_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã KH không hợp lệ..
        /// </summary>
        public static string INVALID_CUSTOMER_ID {
            get {
                return ResourceManager.GetString("INVALID_CUSTOMER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thanh toán xe máy điện không hợp lệ..
        /// </summary>
        public static string INVALID_ES_PAID_CODE {
            get {
                return ResourceManager.GetString("INVALID_ES_PAID_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu thời gian thanh toán không hợp lệ..
        /// </summary>
        public static string INVALID_ES_PAID_DATE {
            get {
                return ResourceManager.GetString("INVALID_ES_PAID_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã dữ liệu không hợp lệ..
        /// </summary>
        public static string INVALID_IDS {
            get {
                return ResourceManager.GetString("INVALID_IDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thay đổi trạng thái xác nhận thông tin hợp lệ nếu đã được xác nhận trước đó.
        /// </summary>
        public static string INVALID_INFO_VALID {
            get {
                return ResourceManager.GetString("INVALID_INFO_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số tiền điều chỉnh và số tiền gốc phải lớn hơn 0..
        /// </summary>
        public static string INVALID_INPUT_AMOUNT_ADJUSTMENT {
            get {
                return ResourceManager.GetString("INVALID_INPUT_AMOUNT_ADJUSTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odo input nhỏ hơn odo đầu tháng.
        /// </summary>
        public static string INVALID_INPUT_ODO {
            get {
                return ResourceManager.GetString("INVALID_INPUT_ODO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin hoá đơn GTGT không hợp lệ.
        /// </summary>
        public static string INVALID_INVOICE_INFO {
            get {
                return ResourceManager.GetString("INVALID_INVOICE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đặt hàng không hợp lệ..
        /// </summary>
        public static string INVALID_ORDER_INFO {
            get {
                return ResourceManager.GetString("INVALID_ORDER_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin phân trang không hợp lệ..
        /// </summary>
        public static string INVALID_PAGING {
            get {
                return ResourceManager.GetString("INVALID_PAGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cá nhân không hợp lệ.
        /// </summary>
        public static string INVALID_PERSONAL_INFO {
            get {
                return ResourceManager.GetString("INVALID_PERSONAL_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin người đại diện không hợp lệ..
        /// </summary>
        public static string INVALID_REPRESENTATIVE_INFO {
            get {
                return ResourceManager.GetString("INVALID_REPRESENTATIVE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tham số tìm kiếm không hợp lệ..
        /// </summary>
        public static string INVALID_SPECIFICATION {
            get {
                return ResourceManager.GetString("INVALID_SPECIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin trạng thái không hợp lệ..
        /// </summary>
        public static string INVALID_STATUS {
            get {
                return ResourceManager.GetString("INVALID_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cửa hàng không hợp lệ.
        /// </summary>
        public static string INVALID_STORE_INFO {
            get {
                return ResourceManager.GetString("INVALID_STORE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã giao dịch không hợp lệ..
        /// </summary>
        public static string INVALID_TRASACTION_ID {
            get {
                return ResourceManager.GetString("INVALID_TRASACTION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phương tiện không hợp lệ..
        /// </summary>
        public static string INVALID_VEHICLE_ID {
            get {
                return ResourceManager.GetString("INVALID_VEHICLE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin xuấthoá đơn..
        /// </summary>
        public static string INVOICE_INFO_NOTFOUND {
            get {
                return ResourceManager.GetString("INVOICE_INFO_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất hoá đơn bị lỗi.
        /// </summary>
        public static string INVOICE_SAP_JOB_FAILED {
            get {
                return ResourceManager.GetString("INVOICE_SAP_JOB_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi thanh lý hợp đồng thuê pin..
        /// </summary>
        public static string LiquidateBatterySubscriptionFailed {
            get {
                return ResourceManager.GetString("LiquidateBatterySubscriptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hết thời gian tạm khoá hoá đơn..
        /// </summary>
        public static string LOCK_BILL_TIMEOUT_EXCEED {
            get {
                return ResourceManager.GetString("LOCK_BILL_TIMEOUT_EXCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu đa ngôn ngữ.
        /// </summary>
        public static string MULTILINGUAL_DATA_NOTFOUND {
            get {
                return ResourceManager.GetString("MULTILINGUAL_DATA_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể tạo hợp đồng mà không đồng ý với phụ lục hợp đồng .
        /// </summary>
        public static string NOT_ALLOW_CREATE_CONTRACT_WITHOUT_SUBCONTRACT {
            get {
                return ResourceManager.GetString("NOT_ALLOW_CREATE_CONTRACT_WITHOUT_SUBCONTRACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ ko được hỗ trợ..
        /// </summary>
        public static string NOT_SUPPORTED_LANGUAGE {
            get {
                return ResourceManager.GetString("NOT_SUPPORTED_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không tồn tại.
        /// </summary>
        public static string NotExist {
            get {
                return ResourceManager.GetString("NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job phí phạt trả chậm bị lỗi..
        /// </summary>
        public static string PENALTY_ARREARS_JOB_FAILED {
            get {
                return ResourceManager.GetString("PENALTY_ARREARS_JOB_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày áp dụng không được để trống hoặc nhỏ hơn ngày hiện tại.
        /// </summary>
        public static string PenaltyConfigurationAppliedDate {
            get {
                return ResourceManager.GetString("PenaltyConfigurationAppliedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá áp dụng phải lớn hơn 0.
        /// </summary>
        public static string PenaltyConfigurationAppliedPrice {
            get {
                return ResourceManager.GetString("PenaltyConfigurationAppliedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn trạm sạc.
        /// </summary>
        public static string PenaltyConfigurationChargingStationId {
            get {
                return ResourceManager.GetString("PenaltyConfigurationChargingStationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn phí phạt.
        /// </summary>
        public static string PenaltyConfigurationPenaltyConfigurationType {
            get {
                return ResourceManager.GetString("PenaltyConfigurationPenaltyConfigurationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi gửi dữ liệu sang DMS..
        /// </summary>
        public static string PostBatterySubscriptionFailed {
            get {
                return ResourceManager.GetString("PostBatterySubscriptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin khoá chính không hợp lệ..
        /// </summary>
        public static string PRIMARY_KEY_SPEC_NOTFOUND {
            get {
                return ResourceManager.GetString("PRIMARY_KEY_SPEC_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy yêu cầu điều chỉnh..
        /// </summary>
        public static string REQUEST_ADJUSTMENT_NOTFOUND {
            get {
                return ResourceManager.GetString("REQUEST_ADJUSTMENT_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi SAP callback..
        /// </summary>
        public static string SAP_CALLBACK_FAILED {
            get {
                return ResourceManager.GetString("SAP_CALLBACK_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy mã giao dịch SAP..
        /// </summary>
        public static string SAP_TRANSACTION_NOTFOUND {
            get {
                return ResourceManager.GetString("SAP_TRANSACTION_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi tìm kiếm SR..
        /// </summary>
        public static string SEARCH_DMS_SHOWROOM_FAILED {
            get {
                return ResourceManager.GetString("SEARCH_DMS_SHOWROOM_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cửa hàng là bắt buộc.
        /// </summary>
        public static string STORE_INFO_REQUIRED {
            get {
                return ResourceManager.GetString("STORE_INFO_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi đồng bộ xuống SAP.
        /// </summary>
        public static string SYCN_TO_SAP_FAILED {
            get {
                return ResourceManager.GetString("SYCN_TO_SAP_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi khi huỷ hợp đồng trên SAP: {0}.
        /// </summary>
        public static string TERNINATE_CONTRACT_SAP_FAILED {
            get {
                return ResourceManager.GetString("TERNINATE_CONTRACT_SAP_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập mã giao dịch.
        /// </summary>
        public static string TRANSACTION_ID_REQUIRED {
            get {
                return ResourceManager.GetString("TRANSACTION_ID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message was not defined yet.
        /// </summary>
        public static string UNDEFINED_MESSAGE {
            get {
                return ResourceManager.GetString("UNDEFINED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang nợ cước thuê pin.
        /// </summary>
        public static string UNPAID_DEBT_LEASING_2106 {
            get {
                return ResourceManager.GetString("UNPAID_DEBT_LEASING_2106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi cập nhật dữ liệu trụ sạc..
        /// </summary>
        public static string UPDATE_CHARGINGSTATION_FAILED {
            get {
                return ResourceManager.GetString("UPDATE_CHARGINGSTATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi cập nhật dữ liệu..
        /// </summary>
        public static string UPDATE_DOC_ERROR {
            get {
                return ResourceManager.GetString("UPDATE_DOC_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi khi cập nhật {0}..
        /// </summary>
        public static string UpdatedError {
            get {
                return ResourceManager.GetString("UpdatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chỉ được cập nhật tài khoản của mình..
        /// </summary>
        public static string UserPermissionUpdateOtherUserError {
            get {
                return ResourceManager.GetString("UserPermissionUpdateOtherUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy hoá đơn.
        /// </summary>
        public static string VOUCHER_NOTFOUND {
            get {
                return ResourceManager.GetString("VOUCHER_NOTFOUND", resourceCulture);
            }
        }
    }
}
