//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChargeHub.Resource {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Label {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Label() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ChargeHub.Resource.Label", typeof(Label).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        public static string BankInformation {
            get {
                return ResourceManager.GetString("BankInformation", resourceCulture);
            }
        }
        
        public static string BANK_TRANSFER {
            get {
                return ResourceManager.GetString("BANK_TRANSFER", resourceCulture);
            }
        }
        
        public static string BatteryPackage {
            get {
                return ResourceManager.GetString("BatteryPackage", resourceCulture);
            }
        }
        
        public static string BatteryProblemBillTitle {
            get {
                return ResourceManager.GetString("BatteryProblemBillTitle", resourceCulture);
            }
        }
        
        public static string BatterySubscription {
            get {
                return ResourceManager.GetString("BatterySubscription", resourceCulture);
            }
        }
        
        public static string BATTERY_CHARGING {
            get {
                return ResourceManager.GetString("BATTERY_CHARGING", resourceCulture);
            }
        }
        
        public static string BATTERY_CHARGING_OTHER_FEES {
            get {
                return ResourceManager.GetString("BATTERY_CHARGING_OTHER_FEES", resourceCulture);
            }
        }
        
        public static string BATTERY_CHARGING_OTHER_FEES_ADJUSTMENT {
            get {
                return ResourceManager.GetString("BATTERY_CHARGING_OTHER_FEES_ADJUSTMENT", resourceCulture);
            }
        }
        
        public static string BATTERY_LEASING {
            get {
                return ResourceManager.GetString("BATTERY_LEASING", resourceCulture);
            }
        }
        
        public static string BATTERY_LEASING_OTHER_FEES {
            get {
                return ResourceManager.GetString("BATTERY_LEASING_OTHER_FEES", resourceCulture);
            }
        }
        
        public static string BATTERY_LEASING_OTHER_FEES_ADJUSTMENT {
            get {
                return ResourceManager.GetString("BATTERY_LEASING_OTHER_FEES_ADJUSTMENT", resourceCulture);
            }
        }
        
        public static string BATTERY_PAYMENT_ARREARS {
            get {
                return ResourceManager.GetString("BATTERY_PAYMENT_ARREARS", resourceCulture);
            }
        }
        
        public static string BATTERY_PAYMENT_ARREARS_ADJUSTMENT {
            get {
                return ResourceManager.GetString("BATTERY_PAYMENT_ARREARS_ADJUSTMENT", resourceCulture);
            }
        }
        
        public static string BATTERY_PROBLEMS_FEE {
            get {
                return ResourceManager.GetString("BATTERY_PROBLEMS_FEE", resourceCulture);
            }
        }
        
        public static string BATTERY_PROBLEMS_FEE_ADJUSTMENT {
            get {
                return ResourceManager.GetString("BATTERY_PROBLEMS_FEE_ADJUSTMENT", resourceCulture);
            }
        }
        
        public static string BILL_CHARGING_ADJUSTMENT_FEE {
            get {
                return ResourceManager.GetString("BILL_CHARGING_ADJUSTMENT_FEE", resourceCulture);
            }
        }
        
        public static string BILL_LEASING_ADJUSTMENT_FEE {
            get {
                return ResourceManager.GetString("BILL_LEASING_ADJUSTMENT_FEE", resourceCulture);
            }
        }
        
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        public static string CARD_PAYMENT {
            get {
                return ResourceManager.GetString("CARD_PAYMENT", resourceCulture);
            }
        }
        
        public static string CASH {
            get {
                return ResourceManager.GetString("CASH", resourceCulture);
            }
        }
        
        public static string ChargeCompleted {
            get {
                return ResourceManager.GetString("ChargeCompleted", resourceCulture);
            }
        }
        
        public static string Charging {
            get {
                return ResourceManager.GetString("Charging", resourceCulture);
            }
        }
        
        public static string ChargingConfiguration {
            get {
                return ResourceManager.GetString("ChargingConfiguration", resourceCulture);
            }
        }
        
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string EsChargingBillTitle {
            get {
                return ResourceManager.GetString("EsChargingBillTitle", resourceCulture);
            }
        }
        
        public static string ESCOOTER_BATTERY_CHARGING {
            get {
                return ResourceManager.GetString("ESCOOTER_BATTERY_CHARGING", resourceCulture);
            }
        }
        
        public static string ESCOOTER_BATTERY_CHARGING_ADJUSTMENT {
            get {
                return ResourceManager.GetString("ESCOOTER_BATTERY_CHARGING_ADJUSTMENT", resourceCulture);
            }
        }
        
        public static string ESCOOTER_BATTERY_LEASING {
            get {
                return ResourceManager.GetString("ESCOOTER_BATTERY_LEASING", resourceCulture);
            }
        }
        
        public static string ESCOOTER_BATTERY_LEASING_ADJUSTMENT {
            get {
                return ResourceManager.GetString("ESCOOTER_BATTERY_LEASING_ADJUSTMENT", resourceCulture);
            }
        }
        
        public static string ESCOOTER_BATTERY_PAYMENT_ARREARS {
            get {
                return ResourceManager.GetString("ESCOOTER_BATTERY_PAYMENT_ARREARS", resourceCulture);
            }
        }
        
        public static string ESCOOTER_BATTERY_PAYMENT_ARREARS_ADJUSTMENT {
            get {
                return ResourceManager.GetString("ESCOOTER_BATTERY_PAYMENT_ARREARS_ADJUSTMENT", resourceCulture);
            }
        }
        
        public static string ESCOOTER_BATTERY_PROBLEMS_FEE {
            get {
                return ResourceManager.GetString("ESCOOTER_BATTERY_PROBLEMS_FEE", resourceCulture);
            }
        }
        
        public static string ESCOOTER_BATTERY_PROBLEMS_FEE_ADJUSTMENT {
            get {
                return ResourceManager.GetString("ESCOOTER_BATTERY_PROBLEMS_FEE_ADJUSTMENT", resourceCulture);
            }
        }
        
        public static string EsLeasingBillTitle {
            get {
                return ResourceManager.GetString("EsLeasingBillTitle", resourceCulture);
            }
        }
        
        public static string F1 {
            get {
                return ResourceManager.GetString("F1", resourceCulture);
            }
        }
        
        public static string F2 {
            get {
                return ResourceManager.GetString("F2", resourceCulture);
            }
        }
        
        public static string F3 {
            get {
                return ResourceManager.GetString("F3", resourceCulture);
            }
        }
        
        public static string F5 {
            get {
                return ResourceManager.GetString("F5", resourceCulture);
            }
        }
        
        public static string F6 {
            get {
                return ResourceManager.GetString("F6", resourceCulture);
            }
        }
        
        public static string Fixed {
            get {
                return ResourceManager.GetString("Fixed", resourceCulture);
            }
        }
        
        public static string Flexible {
            get {
                return ResourceManager.GetString("Flexible", resourceCulture);
            }
        }
        
        public static string INACTIVE {
            get {
                return ResourceManager.GetString("INACTIVE", resourceCulture);
            }
        }
        
        public static string Init {
            get {
                return ResourceManager.GetString("Init", resourceCulture);
            }
        }
        
        public static string INTERNALPAY {
            get {
                return ResourceManager.GetString("INTERNALPAY", resourceCulture);
            }
        }
        
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        public static string Noshow {
            get {
                return ResourceManager.GetString("Noshow", resourceCulture);
            }
        }
        
        public static string NotSelfBooking {
            get {
                return ResourceManager.GetString("NotSelfBooking", resourceCulture);
            }
        }
        
        public static string ONEPAY {
            get {
                return ResourceManager.GetString("ONEPAY", resourceCulture);
            }
        }
        
        public static string Onhold {
            get {
                return ResourceManager.GetString("Onhold", resourceCulture);
            }
        }
        
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        public static string PaidStatus {
            get {
                return ResourceManager.GetString("PaidStatus", resourceCulture);
            }
        }
        
        public static string PayBill {
            get {
                return ResourceManager.GetString("PayBill", resourceCulture);
            }
        }
        
        public static string PenaltyConfiguration {
            get {
                return ResourceManager.GetString("PenaltyConfiguration", resourceCulture);
            }
        }
        
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        public static string PolicyPackage {
            get {
                return ResourceManager.GetString("PolicyPackage", resourceCulture);
            }
        }
        
        public static string PROMOTION {
            get {
                return ResourceManager.GetString("PROMOTION", resourceCulture);
            }
        }
        
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        public static string SelfBooking {
            get {
                return ResourceManager.GetString("SelfBooking", resourceCulture);
            }
        }
        
        public static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        public static string Terminated {
            get {
                return ResourceManager.GetString("Terminated", resourceCulture);
            }
        }
        
        public static string UnPaidStatus {
            get {
                return ResourceManager.GetString("UnPaidStatus", resourceCulture);
            }
        }
        
        public static string UserPermission {
            get {
                return ResourceManager.GetString("UserPermission", resourceCulture);
            }
        }
        
        public static string Whitelist {
            get {
                return ResourceManager.GetString("Whitelist", resourceCulture);
            }
        }
    }
}
