//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChargeHub.Resource
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SuccessMessages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuccessMessages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChargeHub.Resource.SuccessMessages", typeof(SuccessMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tạo {0} thành công.
        /// </summary>
        public static string CreateSuccess
        {
            get
            {
                return ResourceManager.GetString("CreateSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Xóa {0} thành công.
        /// </summary>
        public static string DeleteSuccess
        {
            get
            {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thực hiện {0} thành công.
        /// </summary>
        public static string ExecuteSuccess
        {
            get
            {
                return ResourceManager.GetString("ExecuteSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Chấm dứt hợp đồng thành công.
        /// </summary>
        public static string LiquidateBatterySubcriptionSuccess
        {
            get
            {
                return ResourceManager.GetString("LiquidateBatterySubcriptionSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cập nhật {0} thành công.
        /// </summary>
        public static string UpdateSuccess
        {
            get
            {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }

        public static string Success
        {
            get
            {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
    }
}
